/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sudoku_Final;

import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Sudoku_2 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    Kernel ker = new Kernel();
    Generator gen = new Generator();
    int [][] sudoku = gen.sudoku2;
    
    public Sudoku_2() {
        initComponents();
        updateGui();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        jTextField32 = new javax.swing.JTextField();
        jTextField33 = new javax.swing.JTextField();
        jTextField34 = new javax.swing.JTextField();
        jTextField35 = new javax.swing.JTextField();
        jTextField36 = new javax.swing.JTextField();
        jTextField37 = new javax.swing.JTextField();
        jTextField38 = new javax.swing.JTextField();
        jTextField39 = new javax.swing.JTextField();
        jTextField40 = new javax.swing.JTextField();
        jTextField41 = new javax.swing.JTextField();
        jTextField42 = new javax.swing.JTextField();
        jTextField43 = new javax.swing.JTextField();
        jTextField44 = new javax.swing.JTextField();
        jTextField45 = new javax.swing.JTextField();
        jTextField46 = new javax.swing.JTextField();
        jTextField47 = new javax.swing.JTextField();
        jTextField48 = new javax.swing.JTextField();
        jTextField49 = new javax.swing.JTextField();
        jTextField50 = new javax.swing.JTextField();
        jTextField51 = new javax.swing.JTextField();
        jTextField52 = new javax.swing.JTextField();
        jTextField53 = new javax.swing.JTextField();
        jTextField54 = new javax.swing.JTextField();
        jTextField55 = new javax.swing.JTextField();
        jTextField56 = new javax.swing.JTextField();
        jTextField57 = new javax.swing.JTextField();
        jTextField58 = new javax.swing.JTextField();
        jTextField59 = new javax.swing.JTextField();
        jTextField60 = new javax.swing.JTextField();
        jTextField61 = new javax.swing.JTextField();
        jTextField62 = new javax.swing.JTextField();
        jTextField63 = new javax.swing.JTextField();
        jTextField64 = new javax.swing.JTextField();
        jTextField65 = new javax.swing.JTextField();
        jTextField66 = new javax.swing.JTextField();
        jTextField67 = new javax.swing.JTextField();
        jTextField68 = new javax.swing.JTextField();
        jTextField69 = new javax.swing.JTextField();
        jTextField70 = new javax.swing.JTextField();
        jTextField71 = new javax.swing.JTextField();
        jTextField72 = new javax.swing.JTextField();
        jTextField73 = new javax.swing.JTextField();
        jTextField74 = new javax.swing.JTextField();
        jTextField75 = new javax.swing.JTextField();
        jTextField76 = new javax.swing.JTextField();
        jTextField77 = new javax.swing.JTextField();
        jTextField78 = new javax.swing.JTextField();
        jTextField79 = new javax.swing.JTextField();
        jTextField80 = new javax.swing.JTextField();
        jTextField81 = new javax.swing.JTextField();
        JButton1 = new javax.swing.JButton();
        JButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(9, 9));
        jPanel1.add(jTextField1);
        jPanel1.add(jTextField2);
        jPanel1.add(jTextField3);

        jTextField4.setBackground(new java.awt.Color(0, 0, 0));
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField4);

        jTextField5.setBackground(new java.awt.Color(0, 0, 0));
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField5);

        jTextField6.setBackground(new java.awt.Color(0, 0, 0));
        jTextField6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField6);
        jPanel1.add(jTextField7);
        jPanel1.add(jTextField8);
        jPanel1.add(jTextField9);
        jPanel1.add(jTextField10);
        jPanel1.add(jTextField11);
        jPanel1.add(jTextField12);

        jTextField13.setBackground(new java.awt.Color(0, 0, 0));
        jTextField13.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField13);

        jTextField14.setBackground(new java.awt.Color(0, 0, 0));
        jTextField14.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField14);

        jTextField15.setBackground(new java.awt.Color(0, 0, 0));
        jTextField15.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField15);
        jPanel1.add(jTextField16);
        jPanel1.add(jTextField17);
        jPanel1.add(jTextField18);
        jPanel1.add(jTextField19);
        jPanel1.add(jTextField20);
        jPanel1.add(jTextField21);

        jTextField22.setBackground(new java.awt.Color(0, 0, 0));
        jTextField22.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField22);

        jTextField23.setBackground(new java.awt.Color(0, 0, 0));
        jTextField23.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField23);

        jTextField24.setBackground(new java.awt.Color(0, 0, 0));
        jTextField24.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField24);
        jPanel1.add(jTextField25);
        jPanel1.add(jTextField26);
        jPanel1.add(jTextField27);

        jTextField28.setBackground(new java.awt.Color(0, 0, 0));
        jTextField28.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField28);

        jTextField29.setBackground(new java.awt.Color(0, 0, 0));
        jTextField29.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField29);

        jTextField30.setBackground(new java.awt.Color(0, 0, 0));
        jTextField30.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField30);
        jPanel1.add(jTextField31);
        jPanel1.add(jTextField32);
        jPanel1.add(jTextField33);

        jTextField34.setBackground(new java.awt.Color(0, 0, 0));
        jTextField34.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField34);

        jTextField35.setBackground(new java.awt.Color(0, 0, 0));
        jTextField35.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField35);

        jTextField36.setBackground(new java.awt.Color(0, 0, 0));
        jTextField36.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField36);

        jTextField37.setBackground(new java.awt.Color(0, 0, 0));
        jTextField37.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField37);

        jTextField38.setBackground(new java.awt.Color(0, 0, 0));
        jTextField38.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField38);

        jTextField39.setBackground(new java.awt.Color(0, 0, 0));
        jTextField39.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField39);
        jPanel1.add(jTextField40);
        jPanel1.add(jTextField41);
        jPanel1.add(jTextField42);

        jTextField43.setBackground(new java.awt.Color(0, 0, 0));
        jTextField43.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField43);

        jTextField44.setBackground(new java.awt.Color(0, 0, 0));
        jTextField44.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField44);

        jTextField45.setBackground(new java.awt.Color(0, 0, 0));
        jTextField45.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField45);

        jTextField46.setBackground(new java.awt.Color(0, 0, 0));
        jTextField46.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField46);

        jTextField47.setBackground(new java.awt.Color(0, 0, 0));
        jTextField47.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField47);

        jTextField48.setBackground(new java.awt.Color(0, 0, 0));
        jTextField48.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField48);
        jPanel1.add(jTextField49);
        jPanel1.add(jTextField50);
        jPanel1.add(jTextField51);

        jTextField52.setBackground(new java.awt.Color(0, 0, 0));
        jTextField52.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField52);

        jTextField53.setBackground(new java.awt.Color(0, 0, 0));
        jTextField53.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField53);

        jTextField54.setBackground(new java.awt.Color(0, 0, 0));
        jTextField54.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField54);
        jPanel1.add(jTextField55);
        jPanel1.add(jTextField56);
        jPanel1.add(jTextField57);

        jTextField58.setBackground(new java.awt.Color(0, 0, 0));
        jTextField58.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField58);

        jTextField59.setBackground(new java.awt.Color(0, 0, 0));
        jTextField59.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField59);

        jTextField60.setBackground(new java.awt.Color(0, 0, 0));
        jTextField60.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField60);
        jPanel1.add(jTextField61);
        jPanel1.add(jTextField62);
        jPanel1.add(jTextField63);
        jPanel1.add(jTextField64);
        jPanel1.add(jTextField65);
        jPanel1.add(jTextField66);

        jTextField67.setBackground(new java.awt.Color(0, 0, 0));
        jTextField67.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField67);

        jTextField68.setBackground(new java.awt.Color(0, 0, 0));
        jTextField68.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField68);

        jTextField69.setBackground(new java.awt.Color(0, 0, 0));
        jTextField69.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField69);
        jPanel1.add(jTextField70);
        jPanel1.add(jTextField71);
        jPanel1.add(jTextField72);
        jPanel1.add(jTextField73);
        jPanel1.add(jTextField74);
        jPanel1.add(jTextField75);

        jTextField76.setBackground(new java.awt.Color(0, 0, 0));
        jTextField76.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField76);

        jTextField77.setBackground(new java.awt.Color(0, 0, 0));
        jTextField77.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField77);

        jTextField78.setBackground(new java.awt.Color(0, 0, 0));
        jTextField78.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField78);
        jPanel1.add(jTextField79);
        jPanel1.add(jTextField80);
        jPanel1.add(jTextField81);

        JButton1.setText("Submit");
        JButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton1ActionPerformed(evt);
            }
        });

        JButton2.setText("Solve");
        JButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(JButton2)
                        .addGap(42, 42, 42)
                        .addComponent(JButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JButton1)
                    .addComponent(JButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton1ActionPerformed
       update();
       boolean result = new Violater().Validate(sudoku);
       JOptionPane.showMessageDialog(null, result);
    }//GEN-LAST:event_JButton1ActionPerformed

    private void JButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton2ActionPerformed
        // TODO add your handling code here:
        boolean result = new Violater().Validate(sudoku);
        if(result)
            sudoku = ker.sudokuSolver(sudoku);
        else
            JOptionPane.showMessageDialog(null, "Invalid sudoku");
        updateGui();
    }//GEN-LAST:event_JButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButton1;
    private javax.swing.JButton JButton2;
    private javax.swing.JPanel jPanel1;
    protected javax.swing.JTextField jTextField1;
    protected javax.swing.JTextField jTextField10;
    protected javax.swing.JTextField jTextField11;
    protected javax.swing.JTextField jTextField12;
    protected javax.swing.JTextField jTextField13;
    protected javax.swing.JTextField jTextField14;
    protected javax.swing.JTextField jTextField15;
    protected javax.swing.JTextField jTextField16;
    protected javax.swing.JTextField jTextField17;
    protected javax.swing.JTextField jTextField18;
    protected javax.swing.JTextField jTextField19;
    protected javax.swing.JTextField jTextField2;
    protected javax.swing.JTextField jTextField20;
    protected javax.swing.JTextField jTextField21;
    protected javax.swing.JTextField jTextField22;
    protected javax.swing.JTextField jTextField23;
    protected javax.swing.JTextField jTextField24;
    protected javax.swing.JTextField jTextField25;
    protected javax.swing.JTextField jTextField26;
    protected javax.swing.JTextField jTextField27;
    protected javax.swing.JTextField jTextField28;
    protected javax.swing.JTextField jTextField29;
    protected javax.swing.JTextField jTextField3;
    protected javax.swing.JTextField jTextField30;
    protected javax.swing.JTextField jTextField31;
    protected javax.swing.JTextField jTextField32;
    protected javax.swing.JTextField jTextField33;
    protected javax.swing.JTextField jTextField34;
    protected javax.swing.JTextField jTextField35;
    protected javax.swing.JTextField jTextField36;
    protected javax.swing.JTextField jTextField37;
    protected javax.swing.JTextField jTextField38;
    protected javax.swing.JTextField jTextField39;
    protected javax.swing.JTextField jTextField4;
    protected javax.swing.JTextField jTextField40;
    protected javax.swing.JTextField jTextField41;
    protected javax.swing.JTextField jTextField42;
    protected javax.swing.JTextField jTextField43;
    protected javax.swing.JTextField jTextField44;
    protected javax.swing.JTextField jTextField45;
    protected javax.swing.JTextField jTextField46;
    protected javax.swing.JTextField jTextField47;
    protected javax.swing.JTextField jTextField48;
    protected javax.swing.JTextField jTextField49;
    protected javax.swing.JTextField jTextField5;
    protected javax.swing.JTextField jTextField50;
    protected javax.swing.JTextField jTextField51;
    protected javax.swing.JTextField jTextField52;
    protected javax.swing.JTextField jTextField53;
    protected javax.swing.JTextField jTextField54;
    protected javax.swing.JTextField jTextField55;
    protected javax.swing.JTextField jTextField56;
    protected javax.swing.JTextField jTextField57;
    protected javax.swing.JTextField jTextField58;
    protected javax.swing.JTextField jTextField59;
    protected javax.swing.JTextField jTextField6;
    protected javax.swing.JTextField jTextField60;
    protected javax.swing.JTextField jTextField61;
    protected javax.swing.JTextField jTextField62;
    protected javax.swing.JTextField jTextField63;
    protected javax.swing.JTextField jTextField64;
    protected javax.swing.JTextField jTextField65;
    protected javax.swing.JTextField jTextField66;
    protected javax.swing.JTextField jTextField67;
    protected javax.swing.JTextField jTextField68;
    protected javax.swing.JTextField jTextField69;
    protected javax.swing.JTextField jTextField7;
    protected javax.swing.JTextField jTextField70;
    protected javax.swing.JTextField jTextField71;
    protected javax.swing.JTextField jTextField72;
    protected javax.swing.JTextField jTextField73;
    protected javax.swing.JTextField jTextField74;
    protected javax.swing.JTextField jTextField75;
    protected javax.swing.JTextField jTextField76;
    protected javax.swing.JTextField jTextField77;
    protected javax.swing.JTextField jTextField78;
    protected javax.swing.JTextField jTextField79;
    protected javax.swing.JTextField jTextField8;
    protected javax.swing.JTextField jTextField80;
    protected javax.swing.JTextField jTextField81;
    protected javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

    private void update() {
        sudoku[0][0] = Integer.parseInt(String.valueOf(((jTextField1.getText()).charAt(0))));
        sudoku[0][1] = Integer.parseInt(String.valueOf((jTextField2.getText()).charAt(0)));
        sudoku[0][2] = Integer.parseInt(String.valueOf((jTextField3.getText()).charAt(0)));
        sudoku[0][3] = Integer.parseInt(String.valueOf((jTextField4.getText()).charAt(0)));
        sudoku[0][4] = Integer.parseInt(String.valueOf((jTextField5.getText()).charAt(0)));
        sudoku[0][5] = Integer.parseInt(String.valueOf((jTextField6.getText()).charAt(0)));
        sudoku[0][6] = Integer.parseInt(String.valueOf((jTextField7.getText()).charAt(0)));
        sudoku[0][7] = Integer.parseInt(String.valueOf((jTextField8.getText()).charAt(0)));
        sudoku[0][8] = Integer.parseInt(String.valueOf((jTextField9.getText()).charAt(0)));
        sudoku[1][0] = Integer.parseInt(String.valueOf((jTextField10.getText()).charAt(0)));
        sudoku[1][1] = Integer.parseInt(String.valueOf((jTextField11.getText()).charAt(0)));
        sudoku[1][2] = Integer.parseInt(String.valueOf((jTextField12.getText()).charAt(0)));
        sudoku[1][3] = Integer.parseInt(String.valueOf((jTextField13.getText()).charAt(0)));
        sudoku[1][4] = Integer.parseInt(String.valueOf((jTextField14.getText()).charAt(0)));
        sudoku[1][5] = Integer.parseInt(String.valueOf((jTextField15.getText()).charAt(0)));
        sudoku[1][6] = Integer.parseInt(String.valueOf((jTextField16.getText()).charAt(0)));
        sudoku[1][7] = Integer.parseInt(String.valueOf((jTextField17.getText()).charAt(0)));
        sudoku[1][8] = Integer.parseInt(String.valueOf((jTextField18.getText()).charAt(0)));
        sudoku[2][0] = Integer.parseInt(String.valueOf((jTextField19.getText()).charAt(0)));
        sudoku[2][1] = Integer.parseInt(String.valueOf((jTextField20.getText()).charAt(0)));
        sudoku[2][2] = Integer.parseInt(String.valueOf((jTextField21.getText()).charAt(0)));
        sudoku[2][3] = Integer.parseInt(String.valueOf((jTextField22.getText()).charAt(0)));
        sudoku[2][4] = Integer.parseInt(String.valueOf((jTextField23.getText()).charAt(0)));
        sudoku[2][5] = Integer.parseInt(String.valueOf((jTextField24.getText()).charAt(0)));
        sudoku[2][6] = Integer.parseInt(String.valueOf((jTextField25.getText()).charAt(0)));
        sudoku[2][7] = Integer.parseInt(String.valueOf((jTextField26.getText()).charAt(0)));
        sudoku[2][8] = Integer.parseInt(String.valueOf((jTextField27.getText()).charAt(0)));
        sudoku[3][0] = Integer.parseInt(String.valueOf((jTextField28.getText()).charAt(0)));
        sudoku[3][1] = Integer.parseInt(String.valueOf((jTextField29.getText()).charAt(0)));
        sudoku[3][2] = Integer.parseInt(String.valueOf((jTextField30.getText()).charAt(0)));
        sudoku[3][3] = Integer.parseInt(String.valueOf((jTextField31.getText()).charAt(0)));
        sudoku[3][4] = Integer.parseInt(String.valueOf((jTextField32.getText()).charAt(0)));
        sudoku[3][5] = Integer.parseInt(String.valueOf((jTextField33.getText()).charAt(0)));
        sudoku[3][6] = Integer.parseInt(String.valueOf((jTextField34.getText()).charAt(0)));
        sudoku[3][7] = Integer.parseInt(String.valueOf((jTextField35.getText()).charAt(0)));
        sudoku[3][8] = Integer.parseInt(String.valueOf((jTextField36.getText()).charAt(0)));
        sudoku[4][0] = Integer.parseInt(String.valueOf((jTextField37.getText()).charAt(0)));
        sudoku[4][1] = Integer.parseInt(String.valueOf((jTextField38.getText()).charAt(0)));
        sudoku[4][2] = Integer.parseInt(String.valueOf((jTextField39.getText()).charAt(0)));
        sudoku[4][3] = Integer.parseInt(String.valueOf((jTextField40.getText()).charAt(0)));
        sudoku[4][4] = Integer.parseInt(String.valueOf((jTextField41.getText()).charAt(0)));
        sudoku[4][5] = Integer.parseInt(String.valueOf((jTextField42.getText()).charAt(0)));
        sudoku[4][6] = Integer.parseInt(String.valueOf((jTextField43.getText()).charAt(0)));
        sudoku[4][7] = Integer.parseInt(String.valueOf((jTextField44.getText()).charAt(0)));
        sudoku[4][8] = Integer.parseInt(String.valueOf((jTextField45.getText()).charAt(0)));
        sudoku[5][0] = Integer.parseInt(String.valueOf((jTextField46.getText()).charAt(0)));
        sudoku[5][1] = Integer.parseInt(String.valueOf((jTextField47.getText()).charAt(0)));
        sudoku[5][2] = Integer.parseInt(String.valueOf((jTextField48.getText()).charAt(0)));
        sudoku[5][3] = Integer.parseInt(String.valueOf((jTextField49.getText()).charAt(0)));
        sudoku[5][4] = Integer.parseInt(String.valueOf((jTextField50.getText()).charAt(0)));
        sudoku[5][5] = Integer.parseInt(String.valueOf((jTextField51.getText()).charAt(0)));
        sudoku[5][6] = Integer.parseInt(String.valueOf((jTextField52.getText()).charAt(0)));
        sudoku[5][7] = Integer.parseInt(String.valueOf((jTextField53.getText()).charAt(0)));
        sudoku[5][8] = Integer.parseInt(String.valueOf((jTextField54.getText()).charAt(0)));
        sudoku[6][0] = Integer.parseInt(String.valueOf((jTextField55.getText()).charAt(0)));
        sudoku[6][1] = Integer.parseInt(String.valueOf((jTextField56.getText()).charAt(0)));
        sudoku[6][2] = Integer.parseInt(String.valueOf((jTextField57.getText()).charAt(0)));
        sudoku[6][3] = Integer.parseInt(String.valueOf((jTextField58.getText()).charAt(0)));
        sudoku[6][4] = Integer.parseInt(String.valueOf((jTextField59.getText()).charAt(0)));
        sudoku[6][5] = Integer.parseInt(String.valueOf((jTextField60.getText()).charAt(0)));
        sudoku[6][6] = Integer.parseInt(String.valueOf((jTextField61.getText()).charAt(0)));
        sudoku[6][7] = Integer.parseInt(String.valueOf((jTextField62.getText()).charAt(0)));
        sudoku[6][8] = Integer.parseInt(String.valueOf((jTextField63.getText()).charAt(0)));
        sudoku[7][0] = Integer.parseInt(String.valueOf((jTextField64.getText()).charAt(0)));
        sudoku[7][1] = Integer.parseInt(String.valueOf((jTextField65.getText()).charAt(0)));
        sudoku[7][2] = Integer.parseInt(String.valueOf((jTextField66.getText()).charAt(0)));
        sudoku[7][3] = Integer.parseInt(String.valueOf((jTextField67.getText()).charAt(0)));
        sudoku[7][4] = Integer.parseInt(String.valueOf((jTextField68.getText()).charAt(0)));
        sudoku[7][5] = Integer.parseInt(String.valueOf((jTextField69.getText()).charAt(0)));
        sudoku[7][6] = Integer.parseInt(String.valueOf((jTextField70.getText()).charAt(0)));
        sudoku[7][7] = Integer.parseInt(String.valueOf((jTextField71.getText()).charAt(0)));
        sudoku[7][8] = Integer.parseInt(String.valueOf((jTextField72.getText()).charAt(0)));
        sudoku[8][0] = Integer.parseInt(String.valueOf((jTextField73.getText()).charAt(0)));
        sudoku[8][1] = Integer.parseInt(String.valueOf((jTextField74.getText()).charAt(0)));
        sudoku[8][2] = Integer.parseInt(String.valueOf((jTextField75.getText()).charAt(0)));
        sudoku[8][3] = Integer.parseInt(String.valueOf((jTextField76.getText()).charAt(0)));
        sudoku[8][4] = Integer.parseInt(String.valueOf((jTextField77.getText()).charAt(0)));
        sudoku[8][5] = Integer.parseInt(String.valueOf((jTextField78.getText()).charAt(0)));
        sudoku[8][6] = Integer.parseInt(String.valueOf((jTextField79.getText()).charAt(0)));
        sudoku[8][7] = Integer.parseInt(String.valueOf((jTextField80.getText()).charAt(0)));
        sudoku[8][8] = Integer.parseInt(String.valueOf((jTextField81.getText()).charAt(0)));
    }

    private void updateGui() {
        jTextField1.setText(String.valueOf(sudoku[0][0]));
        jTextField2.setText(String.valueOf(sudoku[0][1]));
        jTextField3.setText(String.valueOf(sudoku[0][2]));
        jTextField4.setText(String.valueOf(sudoku[0][3]));
        jTextField5.setText(String.valueOf(sudoku[0][4]));
        jTextField6.setText(String.valueOf(sudoku[0][5]));
        jTextField7.setText(String.valueOf(sudoku[0][6]));
        jTextField8.setText(String.valueOf(sudoku[0][7]));
        jTextField9.setText(String.valueOf(sudoku[0][8]));

        jTextField1.setText(String.valueOf(sudoku[0][0]));
        jTextField2.setText(String.valueOf(sudoku[0][1]));
        jTextField3.setText(String.valueOf(sudoku[0][2]));
        jTextField4.setText(String.valueOf(sudoku[0][3]));
        jTextField5.setText(String.valueOf(sudoku[0][4]));
        jTextField6.setText(String.valueOf(sudoku[0][5]));
        jTextField7.setText(String.valueOf(sudoku[0][6]));
        jTextField8.setText(String.valueOf(sudoku[0][7]));
        jTextField9.setText(String.valueOf(sudoku[0][8]));

        jTextField10.setText(String.valueOf(sudoku[1][0]));
        jTextField11.setText(String.valueOf(sudoku[1][1]));
        jTextField12.setText(String.valueOf(sudoku[1][2]));
        jTextField13.setText(String.valueOf(sudoku[1][3]));
        jTextField14.setText(String.valueOf(sudoku[1][4]));
        jTextField15.setText(String.valueOf(sudoku[1][5]));
        jTextField16.setText(String.valueOf(sudoku[1][6]));
        jTextField17.setText(String.valueOf(sudoku[1][7]));
        jTextField18.setText(String.valueOf(sudoku[1][8]));

        jTextField19.setText(String.valueOf(sudoku[2][0]));
        jTextField20.setText(String.valueOf(sudoku[2][1]));
        jTextField21.setText(String.valueOf(sudoku[2][2]));
        jTextField22.setText(String.valueOf(sudoku[2][3]));
        jTextField23.setText(String.valueOf(sudoku[2][4]));
        jTextField24.setText(String.valueOf(sudoku[2][5]));
        jTextField25.setText(String.valueOf(sudoku[2][6]));
        jTextField26.setText(String.valueOf(sudoku[2][7]));
        jTextField27.setText(String.valueOf(sudoku[2][8]));

        jTextField28.setText(String.valueOf(sudoku[3][0]));
        jTextField29.setText(String.valueOf(sudoku[3][1]));
        jTextField30.setText(String.valueOf(sudoku[3][2]));
        jTextField31.setText(String.valueOf(sudoku[3][3]));
        jTextField32.setText(String.valueOf(sudoku[3][4]));
        jTextField33.setText(String.valueOf(sudoku[3][5]));
        jTextField34.setText(String.valueOf(sudoku[3][6]));
        jTextField35.setText(String.valueOf(sudoku[3][7]));
        jTextField36.setText(String.valueOf(sudoku[3][8]));

        jTextField37.setText(String.valueOf(sudoku[4][0]));
        jTextField38.setText(String.valueOf(sudoku[4][1]));
        jTextField39.setText(String.valueOf(sudoku[4][2]));
        jTextField40.setText(String.valueOf(sudoku[4][3]));
        jTextField41.setText(String.valueOf(sudoku[4][4]));
        jTextField42.setText(String.valueOf(sudoku[4][5]));
        jTextField43.setText(String.valueOf(sudoku[4][6]));
        jTextField44.setText(String.valueOf(sudoku[4][7]));
        jTextField45.setText(String.valueOf(sudoku[4][8]));

        jTextField46.setText(String.valueOf(sudoku[5][0]));
        jTextField47.setText(String.valueOf(sudoku[5][1]));
        jTextField48.setText(String.valueOf(sudoku[5][2]));
        jTextField49.setText(String.valueOf(sudoku[5][3]));
        jTextField50.setText(String.valueOf(sudoku[5][4]));
        jTextField51.setText(String.valueOf(sudoku[5][5]));
        jTextField52.setText(String.valueOf(sudoku[5][6]));
        jTextField53.setText(String.valueOf(sudoku[5][7]));
        jTextField54.setText(String.valueOf(sudoku[5][8]));

        jTextField55.setText(String.valueOf(sudoku[6][0]));
        jTextField56.setText(String.valueOf(sudoku[6][1]));
        jTextField57.setText(String.valueOf(sudoku[6][2]));
        jTextField58.setText(String.valueOf(sudoku[6][3]));
        jTextField59.setText(String.valueOf(sudoku[6][4]));
        jTextField60.setText(String.valueOf(sudoku[6][5]));
        jTextField61.setText(String.valueOf(sudoku[6][6]));
        jTextField62.setText(String.valueOf(sudoku[6][7]));
        jTextField63.setText(String.valueOf(sudoku[6][8]));

        jTextField64.setText(String.valueOf(sudoku[7][0]));
        jTextField65.setText(String.valueOf(sudoku[7][1]));
        jTextField66.setText(String.valueOf(sudoku[7][2]));
        jTextField67.setText(String.valueOf(sudoku[7][3]));
        jTextField68.setText(String.valueOf(sudoku[7][4]));
        jTextField69.setText(String.valueOf(sudoku[7][5]));
        jTextField70.setText(String.valueOf(sudoku[7][6]));
        jTextField71.setText(String.valueOf(sudoku[7][7]));
        jTextField72.setText(String.valueOf(sudoku[7][8]));

        jTextField73.setText(String.valueOf(sudoku[8][0]));
        jTextField74.setText(String.valueOf(sudoku[8][1]));
        jTextField75.setText(String.valueOf(sudoku[8][2]));
        jTextField76.setText(String.valueOf(sudoku[8][3]));
        jTextField77.setText(String.valueOf(sudoku[8][4]));
        jTextField78.setText(String.valueOf(sudoku[8][5]));
        jTextField79.setText(String.valueOf(sudoku[8][6]));
        jTextField80.setText(String.valueOf(sudoku[8][7]));
        jTextField81.setText(String.valueOf(sudoku[8][8]));    
    }
}
